[project]
name = "web-scraper"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "curl-cffi>=0.13.0",
    "duckdb>=1.4.1",
    "jupyterlab>=4.4.9",
    "selectolax>=0.4.0",
]
